### ISSUE TITLE
CompatibilityVersion.Version_2_2 causing NRE

### ISSUE THREAD

**Issue by claytondus** [cloudscribe/cloudscribe.Web.Pagination#44] opened 2019-01-16 03:57 UTC
Using cloudscribe.Web.Pagination 2.1.7.  Setting MVC CompatibilityVersion to Version_2_2 causes a NRE when encountering the tag helper. Reverting to Version_2_1 resolves the issue.

```
services
   .AddMvc(options =>
         {
            options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
         })
   .AddRazorPagesOptions(options =>
        {
           options.Conventions.AuthorizeFolder("/");
        })
  .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
  .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```
```
<cs-pager cs-paging-pagesize="@Model.PageSize"
    cs-paging-pagenumber="@Model.PageNumber"
    cs-paging-totalitems="@Model.TotalItems"
    cs-pagenumber-param="page"
    asp-controller="Colors"
    asp-action="Index"></cs-pager>
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at cloudscribe.Web.Pagination.PagerTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore.Views_Colors_Index.ExecuteAsync() in C:\src\agon\Agon.Admin.Mvc\Views\Colors\Index.cshtml:line 81
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
```

**Comment by joeaudette** [comment] 2019-01-16 21:06
There is a new feature introduced in asp.net core 2.2 called EndpointRouting. It has a number of known bugs that will be fixed in 3.0

The workaround for 2.2 is to disable EndpointRouting:

    services.AddMvc(options => {
            options.EnableEndpointRouting = false;
        });

that should solve the problem as I'm using the pager in 2.2 projects with no issues as long as that is disabled.

This is not a bug in the pager library it is a bug in asp.net core 2.2.

**Closed** 2019-01-16 21:21 UTC
